version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_owncloud
      - MARIADB_DATABASE=bitnami_owncloud
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  owncloud:
    image: threefolddev/tf-owncloud:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OWNCLOUD_DATABASE_HOST=mariadb
      - OWNCLOUD_DATABASE_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # Host for accessing ownCloud
      # note: this setting will only be applied on the first run
      # ref: https://github.com/bitnami/bitnami-docker-owncloud#configuration
      - OWNCLOUD_HOST=${OWNCLOUD_HOST}
      - OWNCLOUD_USERNAME=${OWNCLOUD_USERNAME}
      - OWNCLOUD_PASSWORD=${OWNCLOUD_PASSWORD}
      - OWNCLOUD_EMAIL=${OWNCLOUD_EMAIL}
      - OWNCLOUD_SMTP_HOST=${OWNCLOUD_SMTP_HOST}
      - OWNCLOUD_SMTP_PORT_NUMBER=${OWNCLOUD_SMTP_PORT_NUMBER}
      - OWNCLOUD_SMTP_USER=${OWNCLOUD_SMTP_USER}
      - OWNCLOUD_SMTP_PASSWORD=${OWNCLOUD_SMTP_PASSWORD}
      - SUITECRM_SMTP_PROTOCOL=${SUITECRM_SMTP_PROTOCOL}
    volumes:
      - 'owncloud_data:/bitnami/owncloud'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  owncloud_data:
    driver: local